$ErrorActionPreference = "Stop"

Write-Host "=== 2D Point Annotator Installer ==="
Write-Host ""

# -----------------------------
# Configuration
# -----------------------------
$Owner  = "OrthoDriven"
$Repo   = "2d-point-annotator"
$Branch = "new-prototype"

$RepoZipUrl = "https://github.com/$Owner/$Repo/archive/refs/heads/$([uri]::EscapeDataString($Branch)).zip"
$ApiUrl     = "https://api.github.com/repos/$Owner/$Repo/commits/$([uri]::EscapeDataString($Branch))"

$InstallRoot = Join-Path $HOME "2d-point-annotator"
$ZipPath     = Join-Path $InstallRoot "annotator.zip"
$EnvPath     = Join-Path $InstallRoot "app.env"
$ConfigPath  = Join-Path $InstallRoot "config.ps1"

# -----------------------------
# Helpers
# -----------------------------
function Remove-PathIfExists {
    param([Parameter(Mandatory = $true)][string]$PathToRemove)
    if (Test-Path $PathToRemove) {
        Remove-Item -Recurse -Force $PathToRemove
    }
}

# -----------------------------
# Prepare install directory
# -----------------------------
Write-Host "Preparing install directory: $InstallRoot"
New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null
Remove-PathIfExists (Join-Path $InstallRoot "app")
Remove-PathIfExists (Join-Path $InstallRoot "app.new")
Remove-PathIfExists (Join-Path $InstallRoot "app.old")
Get-ChildItem -Path $InstallRoot -Directory -Filter "$Repo-*" -ErrorAction SilentlyContinue | ForEach-Object {
    Remove-Item -Recurse -Force $_.FullName
}

# -----------------------------
# Download + extract
# -----------------------------
Write-Host "Downloading application files from branch: $Branch"
Invoke-WebRequest -Uri $RepoZipUrl -OutFile $ZipPath

Write-Host "Extracting files..."
Expand-Archive -Force $ZipPath $InstallRoot
Remove-Item -Force $ZipPath

$ProjectDir = Get-ChildItem -Path $InstallRoot -Directory -Recurse | Where-Object {
    Test-Path (Join-Path $_.FullName "pixi.toml")
} | Select-Object -First 1

if (-not $ProjectDir) {
    Write-Host "ERROR: Could not locate project directory containing pixi.toml"
    Pause
    exit 1
}

$AppDir = Join-Path $InstallRoot "app"
Move-Item -Force $ProjectDir.FullName $AppDir
Get-ChildItem -Path $InstallRoot -Directory -Filter "$Repo-*" -ErrorAction SilentlyContinue | ForEach-Object {
    Remove-Item -Recurse -Force $_.FullName
}

# -----------------------------
# Persist config for PowerShell helpers
# -----------------------------
@"
`$Owner  = "$Owner"
`$Repo   = "$Repo"
`$Branch = "$Branch"

`$InstallRoot = "$InstallRoot"
`$AppDir      = Join-Path `$InstallRoot "app"
`$StatePath   = Join-Path `$InstallRoot "update_state.json"
`$TempDir     = Join-Path `$InstallRoot "_tmp"

`$UserAgent               = "2d-point-annotator-updater"
`$MinCheckIntervalSeconds = 15
`$RequestTimeoutSec       = 15

`$ZipUrl = "$RepoZipUrl"
`$ApiUrl = "$ApiUrl"
"@ | Set-Content -Path $ConfigPath -Encoding UTF8

# -----------------------------
# Persist app.env for Python updater
# -----------------------------
@"
# Auto-generated by installer
USER_AGENT="2d-point-annotator-updater"
INSTALL_ROOT="$InstallRoot"
PROJECT_DIR="$AppDir"
APP_DIR="$AppDir"
STATE_PATH="$(Join-Path $InstallRoot 'update_state.json')"
REQUEST_TIMEOUT_SEC="15"
MIN_CHECK_INTERVAL_SECONDS="15"
OWNER="$Owner"
REPO="$Repo"
BRANCH="$Branch"
API_URL="$ApiUrl"
REPO_ZIP_URL="$RepoZipUrl"
"@ | Set-Content -Path $EnvPath -Encoding UTF8

# -----------------------------
# Install Pixi if needed
# -----------------------------
$PixiBin = Join-Path $HOME ".pixi\bin"
if (-not ($env:PATH -split ';' | Where-Object { $_ -eq $PixiBin })) {
    $env:PATH = "$env:PATH;$PixiBin"
}

if (-not (Get-Command pixi -ErrorAction SilentlyContinue)) {
    Write-Host "Pixi not found. Installing Pixi..."
    Invoke-RestMethod -UseBasicParsing https://pixi.sh/install.ps1 | Invoke-Expression
    $env:PATH = "$env:PATH;$PixiBin"
}

if (-not (Get-Command pixi -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: Pixi was not found after installation. Try opening a new PowerShell window and re-running the launcher."
    Pause
    exit 1
}

# -----------------------------
# Create desktop launcher
# -----------------------------
$DesktopPath = [Environment]::GetFolderPath("Desktop")
$LauncherPath = Join-Path $DesktopPath "Run_Annotator.bat"
$LauncherPs1 = Join-Path $AppDir "windows_install_scripts\Run_Annotator_Windows.ps1"

@"
@echo off
powershell -ExecutionPolicy Bypass -NoProfile -File "$LauncherPs1"
pause
"@ | Set-Content -Path $LauncherPath -Encoding ASCII

Write-Host ""
Write-Host "Installation complete."
Write-Host "Launcher created at: $LauncherPath"
Write-Host ""
Pause
