#!/usr/bin/env bash
set -euo pipefail

OWNER="OrthoDriven"
REPO="2d-point-annotator"
BRANCH="prototype-tools"

REPO_ZIP_URL="https://github.com/$OWNER/$REPO/archive/refs/heads/$BRANCH.zip"
INSTALL_ROOT="$HOME/2d-point-annotator"
TMP_ZIP_FILE_PATH="$HOME/Downloads/2d-annotator.zip"

if [ -d "$INSTALL_ROOT/app" ]; then
    rm -rf "$INSTALL_ROOT/app/"
fi

mkdir -p "$INSTALL_ROOT"
mkdir -p "$(dirname "$TMP_ZIP_FILE_PATH")"

echo "Downloading application files..."
curl -fsSL "$REPO_ZIP_URL" -o "$TMP_ZIP_FILE_PATH"

echo "Unzipping the files into $INSTALL_ROOT"
unzip -oq "$TMP_ZIP_FILE_PATH" -d "$INSTALL_ROOT"

TMP_PROJECT_DIR="$(find "$INSTALL_ROOT" -type f -name pixi.toml -print0 | xargs -0 dirname | head -n 1)"
PROJECT_DIR="$(dirname "$TMP_PROJECT_DIR")/app"

mv "$TMP_PROJECT_DIR" "$PROJECT_DIR"

if [ -d "$INSTALL_ROOT/old_app" ]; then
    rm -rf "$INSTALL_ROOT/old_app"
fi

if ! command -v pixi >/dev/null 2>&1; then
    echo "No pixi executable found, installing now!"
    curl -fsSL https://pixi.sh/install.sh | sh
else
    echo "Pixi executable found, skipping additional installation."
fi

ENV_FILE="$INSTALL_ROOT/app.env"
mkdir -p "$(dirname "$ENV_FILE")"

cat >"$ENV_FILE" <<EOF
# Auto-generated by installer on $(date)
USER_AGENT="2d-point-annotator-updater"
INSTALL_ROOT="$INSTALL_ROOT"
PROJECT_DIR="$PROJECT_DIR"
APP_DIR="$PROJECT_DIR"
REQUEST_TIMEOUT_SEC="15"
MIN_CHECK_INTERVAL_SECONDS="15"
API_URL="https://api.github.com/repos/$OWNER/$REPO/commits/$BRANCH"
REPO_ZIP_URL="$REPO_ZIP_URL"
EOF

if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "MacOS Detected!"
    ln -sf "$PROJECT_DIR/install_scripts/UnixLauncher.sh" "$HOME/Desktop/Run_Annotator.command"
fi