#!/usr/bin/env bash
set -euo pipefail

OWNER="OrthoDriven"
REPO="2d-point-annotator"
BRANCH="new-prototype"

REPO_ZIP_URL="https://github.com/$OWNER/$REPO/archive/refs/heads/$BRANCH.zip"
API_URL="https://api.github.com/repos/$OWNER/$REPO/commits/$BRANCH"
INSTALL_ROOT="$HOME/2d-point-annotator"
TMP_ZIP_FILE_PATH="$HOME/Downloads/2d-annotator.zip"
ENV_FILE="$INSTALL_ROOT/app.env"

mkdir -p "$INSTALL_ROOT"
mkdir -p "$(dirname "$TMP_ZIP_FILE_PATH")"

if [ -d "$INSTALL_ROOT/app" ]; then
    rm -rf "$INSTALL_ROOT/app"
fi
if [ -d "$INSTALL_ROOT/app.new" ]; then
    rm -rf "$INSTALL_ROOT/app.new"
fi
if [ -d "$INSTALL_ROOT/app.old" ]; then
    rm -rf "$INSTALL_ROOT/app.old"
fi

find "$INSTALL_ROOT" -mindepth 1 -maxdepth 1 -type d -name "$REPO-*" -exec rm -rf {} + 2>/dev/null || true

echo "Downloading application files from branch: $BRANCH"
curl -fsSL "$REPO_ZIP_URL" -o "$TMP_ZIP_FILE_PATH"

echo "Unzipping the files into $INSTALL_ROOT"
unzip -oq "$TMP_ZIP_FILE_PATH" -d "$INSTALL_ROOT"

TMP_PROJECT_DIR="$(find "$INSTALL_ROOT" -type f -name pixi.toml -not -path '*/app.old/*' -not -path '*/app.new/*' -print0 | xargs -0 dirname | head -n 1)"
[ -n "$TMP_PROJECT_DIR" ] || {
    echo "ERROR: Could not find pixi.toml in downloaded archive"
    exit 1
}

PROJECT_DIR="$INSTALL_ROOT/app"
mv "$TMP_PROJECT_DIR" "$PROJECT_DIR"

find "$INSTALL_ROOT" -mindepth 1 -maxdepth 1 -type d -name "$REPO-*" -exec rm -rf {} + 2>/dev/null || true

if ! command -v pixi >/dev/null 2>&1; then
    echo "No pixi executable found, installing now!"
    curl -fsSL https://pixi.sh/install.sh | sh
else
    echo "Pixi executable found, skipping additional installation."
fi

mkdir -p "$(dirname "$ENV_FILE")"
cat >"$ENV_FILE" <<EOF
# Auto-generated by installer on $(date)
USER_AGENT="2d-point-annotator-updater"
INSTALL_ROOT="$INSTALL_ROOT"
PROJECT_DIR="$PROJECT_DIR"
APP_DIR="$PROJECT_DIR"
REQUEST_TIMEOUT_SEC="15"
MIN_CHECK_INTERVAL_SECONDS="15"
OWNER="$OWNER"
REPO="$REPO"
BRANCH="$BRANCH"
API_URL="$API_URL"
REPO_ZIP_URL="$REPO_ZIP_URL"
EOF

if [[ "$OSTYPE" == darwin* ]]; then
    echo "MacOS detected"
    chmod +x "$PROJECT_DIR/install_scripts/UnixLauncher.sh"
    ln -sf "$PROJECT_DIR/install_scripts/UnixLauncher.sh" "$HOME/Desktop/Run_Annotator.command"
fi
