#!/usr/bin/env python3
"""Generate landmarks.tex from hipguide_landmarks.json."""

import json
import sys
from pathlib import Path

PREAMBLE = r"""\newcommand{\landmark}[9]{%
  % #1: Name
  % #2: Acronym
  % #3: Anatomical Feature
  % #4: View(s)
  % #5: Prediction Geometry
  % #6: Type
  % #7: Placement Rules
  % #8: Edge-Case Handling
  % #9: Escalate When
  \subsubsection{#1}
  \noindent
  \textbf{Name:} #1

  \noindent
  \textbf{Acronym:} #2

  \noindent
  \textbf{Underlying Anatomical Feature(s):} #3

  \noindent
  \textbf{View(s):} #4

  \noindent
  \textbf{Prediction Geometry:} #5

  \noindent
  \textbf{Type:} #6

  \noindent
  \textbf{Placement Rules:} #7

  \noindent
  \textbf{Edge-Case Handling:} #8

  \noindent
  \textbf{Escalate When:} #9
}
"""


def format_geometry(geom: dict) -> str:
    gtype = geom["type"]
    count = geom["count"]
    labels = geom.get("labels", [])

    if count == 1:
        return f"1 {gtype}"

    label_str = ", ".join(l.replace("_", r"\_") for l in labels) if labels else ""
    noun = f"{gtype}s" if gtype == "point" else f"{gtype}s"
    return f"{count} {noun} ({label_str})"


def format_placement_rules(rules: dict) -> str:
    if "general" in rules and len(rules) == 1:
        return escape_latex(rules["general"])

    parts = []
    for key, text in rules.items():
        label = key.replace("_", " ").title()
        parts.append(f"\\textit{{{label}:}} {escape_latex(text)}")

    items = "\n    ".join(f"\\item {p}" for p in parts)
    return f"\n\\begin{{itemize}}\n    {items}\n\\end{{itemize}}"


def escape_latex(text: str) -> str:
    if text is None:
        return "[TODO]"
    # Don't escape things that are already LaTeX commands
    # Just handle the common dangerous characters
    # Braces first (before other replacements that introduce backslashes)
    text = text.replace("{", r"\{")
    text = text.replace("}", r"\}")
    text = text.replace("&", r"\&")
    text = text.replace("%", r"\%")
    text = text.replace("#", r"\#")
    text = text.replace("_", r"\_")
    text = text.replace("—", "---")
    text = text.replace("\u2018", "`")  # left single quote
    text = text.replace("\u2019", "'")  # right single quote
    return text


def generate_landmark_entry(lm: dict) -> str:
    name = escape_latex(lm["name"])
    acronym = escape_latex(lm["acronym"])
    anat = escape_latex(lm.get("anatomical_feature") or "[TODO]")
    views = ", ".join(lm["views"])
    geom = format_geometry(lm["prediction_geometry"])
    ltype = lm["landmark_type"].title()
    rules = format_placement_rules(lm["placement_rules"])
    edge = escape_latex(lm.get("edge_cases"))
    escalate = escape_latex(lm.get("escalate_when"))

    formerly = lm.get("formerly")
    comment = f"% {lm['name']}"
    if formerly:
        comment += f" (formerly {formerly})"

    return f"""{comment}
\\landmark{{{name}}}{{{acronym}}}{{{anat}}}{{{views}}}{{{geom}}}{{{ltype}}}{{{rules}}}{{{edge}}}{{{escalate}}}
"""


def main():
    json_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("docs/landmarks.json")
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("docs/landmarks.tex")

    with open(json_path) as f:
        data = json.load(f)

    meta = data["metadata"]
    landmarks = data["landmarks"]
    dropped = data.get("dropped_landmarks", [])

    lines = []
    lines.append(f"% Auto-generated from {json_path.name}")
    lines.append(
        f"% Version: {meta['version']}  |  Product: {meta['product']}  |  Updated: {meta['last_updated']}"
    )
    lines.append(
        f"% DO NOT EDIT THIS FILE DIRECTLY — edit {json_path.name} and regenerate."
    )
    lines.append("")
    lines.append(PREAMBLE)

    for lm in landmarks:
        lines.append(generate_landmark_entry(lm))

    # Append dropped landmarks as comments for traceability
    lines.append("% === Dropped Landmarks ===")
    for d in dropped:
        lines.append(f"% DROPPED: {d['name']} — {d['reason']}")

    output = "\n".join(lines)
    with open(out_path, "w") as f:
        f.write(output)

    print(
        f"Generated {out_path} from {json_path} ({len(landmarks)} landmarks, {len(dropped)} dropped)"
    )


if __name__ == "__main__":
    main()
